# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7-debian
    container_name: mysql-docker
    ports:
      - '3306:3306'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:rw
      - ./backups:/backups/:rw
      - mysql_volume:/var/lib/mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

volumes:
  mysql_volume: